/* Generated by Nim Compiler v1.0.2 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/lib/nim -I/Users/ed/nim/nimacros/src -o /Users/ed/nim/nimacros/src/lixo/stdlib_posix.nim.c.o /Users/ed/nim/nimacros/src/lixo/stdlib_posix.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
int MAP_POPULATE__VA0iC4AP6fJAacff09cx89ag;
N_LIB_PRIVATE N_NIMCALL(void, stdlib_posixInit000)(void) {
{
	MAP_POPULATE__VA0iC4AP6fJAacff09cx89ag = ((int) 0);
}
}

